### ISSUE TITLE
Stupid Question Here (Beginner)

### ISSUE THREAD

**Issue by Littlecris** [crclayton/streamer-locator#5]
I'm more of an HTML Guy. And Just recently got into Python, This isn't an issue, just a request, So, I'd like to know the requirements for installation, I have Python 3.9, (According to some forums geolite isn't supported by it, and The Errors I get are as follows:
ModuleNotFoundError: No module named 'geolite2'.
So what I'm getting from this is that I haven't installed it. In the video, Timestamp 4(:13) I don't know how to access the Python Environments Module. Am I missing something? Someone please tell me.
https://www.youtube.com/watch?v=nPpW3xTKhbE&ab_channel=CharlesClayton

**Comment by janik6882** [comment]
This error means, geolite2 is not installed which you get totally right. You should be able to install it via "pip3 install maxminddb-geolite2" (which is the first line of the programm btw). If this does not work feel free to ask.

**Comment by pdro2907** [comment]
> This error means, geolite2 is not installed which you get totally right. You should be able to install it via "pip3 install maxminddb-geolite2" (which is the first line of the programm btw). If this does not work feel free to ask.

Hi, I already installed the modules and got the same problem, its like the script cant find them. It throw me this

Traceback (most recent call last):
  File "omegle.py", line 3, in <module>
    from geolite2 import geolite2
ImportError: No module named geolite2

**Comment by mesyy1225** [comment]
> > This error means, geolite2 is not installed which you get totally right. You should be able to install it via "pip3 install maxminddb-geolite2" (which is the first line of the programm btw). If this does not work feel free to ask.
> 
> Hi, I already installed the modules and got the same problem, its like the script cant find them. It throw me this
> 
> Traceback (most recent call last):
> File "omegle.py", line 3, in
> from geolite2 import geolite2
> ImportError: No module named geolite2

u can install that package and run the program
